[package]
name = "heroes2"
version = "0.1.0"
authors = ["Tearat"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "20.1.0"
actix-web = "*"
actix-rt = "*"
warp = "0.2"
serde = "*"
toml = "*"